import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Button } from "@marco-polo/button";

import { api } from "~/utils/api";
import { type ReactElement } from "react";

const Home: NextPage = () => {
  const username = api.user.getById.useQuery("clfis22hq000k3b6lucid4jwe");

  return (
    <>
      <Head>
        <title>Create Seat Booking App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
            Create <span>Seat Booking</span> App
          </h1>
          <div>
            <Link
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3>First Steps →</h3>
              <div>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link href="https://create.t3.gg/en/introduction" target="_blank">
              <h3>Documentation →</h3>
              <div>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div>
            <p>
              {username?.data?.name &&
                `the first user in the database is ${username.data.name}`}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase = (): ReactElement => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div>
      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
};
