import { type NextPage } from "next";
import Head from "next/head";
import * as Layout from "../styles/layoutComponents";

import { SeatMap } from "~/components/SeatMap";

const Home: NextPage = () => {
  // const seats = api.seat.getAllSeats.useQuery();

  return (
    <>
      <Head>
        <title>Create Seat Booking App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout.Page>
          <Layout.ResBar>
            <div>
              <h1>Seat Booking Sidebar</h1>
            </div>
          </Layout.ResBar>
          <SeatMap />
        </Layout.Page>
      </main>
    </>
  );
};

export default Home;
