import { type NextPage } from "next";
import Head from "next/head";
import * as Layout from "../styles/layoutComponents";
import { signIn, signOut, useSession } from "next-auth/react";

import { SeatMap } from "~/components/SeatMap";
import { type ReactElement } from "react";
import { SeatContextProvider } from "~/utils/contextHooks/useSeatContext";
import { SeatForm } from "~/components/SeatForm";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Seat Booking App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Layout.Page>
        <SeatContextProvider>
          <Layout.ResBar>
            <h1>Seat Booking Sidebar</h1>
            <AuthShowcase />
            <SeatForm />
          </Layout.ResBar>
          <Layout.MapArea>
            <SeatMap />
          </Layout.MapArea>
        </SeatContextProvider>
      </Layout.Page>
    </main>
  </>
);

export default Home;

const AuthShowcase = (): ReactElement => {
  const { data: sessionData } = useSession();
  return (
    <div>
      <p>{sessionData && <span>Logged in as {sessionData.user?.name}</span>}</p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
